import { FieldValue } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { getPortalUser, isTrustedPortalOrigin } from "@/lib/portalAuth";
import { getAdminFirestore } from "@/lib/firebaseAdmin";
import { requestEvidence } from "@/lib/paymentEvidence";

export async function GET(){const user=await getPortalUser();if(!user||user.role!=="client")return NextResponse.json({error:"Client access required."},{status:401});const db=getAdminFirestore();if(!db)return NextResponse.json({error:"Portal database is not configured."},{status:503});const snapshot=await db.collection("portalClients").doc(user.uid).get();const item=snapshot.data()||{};return NextResponse.json({profile:{name:item.billingProfile?.name||user.name,email:item.billingProfile?.email||user.email,phone:item.billingProfile?.phone||item.phone||"",address1:item.billingProfile?.address1||"",address2:item.billingProfile?.address2||"",city:item.billingProfile?.city||"",state:item.billingProfile?.state||"",zip:item.billingProfile?.zip||"",country:item.billingProfile?.country||"United States"}})}

export async function PATCH(request){if(!isTrustedPortalOrigin(request))return NextResponse.json({error:"Invalid request origin."},{status:403});const user=await getPortalUser();if(!user||user.role!=="client")return NextResponse.json({error:"Client access required."},{status:401});const db=getAdminFirestore();if(!db)return NextResponse.json({error:"Portal database is not configured."},{status:503});try{const body=await request.json();const text=(value,max=180)=>String(value||"").trim().slice(0,max);const profile={name:text(body.name),email:user.email,phone:text(body.phone,40),address1:text(body.address1),address2:text(body.address2),city:text(body.city,100),state:text(body.state,100),zip:text(body.zip,20),country:text(body.country,100),updatedAt:FieldValue.serverTimestamp()};if(!profile.name||!profile.address1||!profile.city||!profile.state||!profile.zip)return NextResponse.json({error:"Name and complete billing address are required."},{status:400});const clientRef=db.collection("portalClients").doc(user.uid);await clientRef.set({billingProfile:profile,updatedAt:FieldValue.serverTimestamp()},{merge:true});await clientRef.collection("auditLog").add({event:"client_billing_profile_updated",actorUid:user.uid,actorRole:user.role,createdAt:FieldValue.serverTimestamp(),fieldsChanged:["name","phone","address1","address2","city","state","zip","country"],...requestEvidence(request)});return NextResponse.json({success:true,profile})}catch{return NextResponse.json({error:"Unable to update billing profile."},{status:500})}}
