import Header from "@/components/ui/Header";
import FooterSection from "@/components/sections/FooterSection";
import Link from "next/link";
import { FaArrowRightLong, FaRegClock, FaRegMessage } from "react-icons/fa6";
import { IoCallSharp } from "react-icons/io5";

export const metadata = { title: "Trademark Filing Support Contact | Legal Trademark Office", description: "Start a U.S. trademark application or contact Legal Trademark Office LLC customer support about an existing order.", alternates: { canonical: "/contact-us" } };

export default function ContactPage() {
  return <><Header /><main className="overflow-hidden bg-white">
    <section className="relative bg-gradient-to-b from-[#ecf9ff] to-white px-5 pb-24 pt-28"><div className="soft-blob -left-16 top-10 bg-blue-200" /><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-2"><div className="relative z-10"><p className="font-bold uppercase tracking-[0.18em] text-[#027DD6]">We are here to help</p><h1 className="mt-4 text-4xl font-bold leading-tight text-slate-900 md:text-6xl">Let’s Find the Right Next Step for Your Trademark</h1><p className="mt-6 text-lg leading-8 text-slate-600">Starting a new application or checking on an existing order? Choose the option that fits and we’ll help you move forward.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/trademark-registration" className="soft-primary-btn">Start a New Filing <FaArrowRightLong /></Link><Link href="tel:+13104244909" className="soft-secondary-btn"><IoCallSharp /> Call Support</Link></div></div><div className="relative"><div className="contact-phone-card rounded-[2rem] bg-white p-8 shadow-2xl"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-[#50c8ee] to-[#027DD6] text-3xl text-white"><IoCallSharp /></span><p className="mt-7 text-sm font-bold uppercase tracking-wide text-[#027DD6]">Customer support</p><a href="tel:+13104244909" className="mt-2 block text-3xl font-bold text-slate-900">+1 (310) 424-4909</a><p className="mt-3 text-slate-600">Monday–Friday · 9:00 AM–6:00 PM</p><div className="mt-7 rounded-2xl bg-[#f1f9ff] p-5"><p className="font-semibold text-slate-800">Already placed an order?</p><p className="mt-2 text-sm leading-6 text-slate-600">Keep your order email or receipt number nearby so our team can locate it quickly.</p></div></div><div className="soft-float-card absolute -bottom-6 -left-5"><FaRegMessage className="text-[#027DD6]" /><span>Friendly filing support</span></div></div></div></section>
    <section className="px-5 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-6 md:grid-cols-2"><article className="rounded-3xl bg-gradient-to-br from-[#e8f8ff] to-white p-8 shadow-sm"><span className="text-sm font-bold uppercase tracking-wide text-[#027DD6]">New customers</span><h2 className="mt-3 text-3xl font-bold text-slate-900">Ready to register a brand?</h2><p className="mt-4 leading-7 text-slate-600">Compare service plans for a business name, logo or slogan and start online.</p><Link href="/trademark-registration" className="mt-7 inline-flex items-center gap-2 font-bold text-[#027DD6]">View registration plans <FaArrowRightLong /></Link></article><article className="rounded-3xl bg-gradient-to-br from-[#fff7e8] to-white p-8 shadow-sm"><span className="text-sm font-bold uppercase tracking-wide text-amber-600">Existing customers</span><h2 className="mt-3 text-3xl font-bold text-slate-900">Need help with an order?</h2><p className="mt-4 leading-7 text-slate-600">Call the support number with your order details and we’ll help identify the next service step.</p><Link href="tel:+13104244909" className="mt-7 inline-flex items-center gap-2 font-bold text-amber-700"><IoCallSharp /> Call customer support</Link></article></div></div></section>
    <section className="bg-[#f5fbff] px-5 py-24"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="font-bold uppercase tracking-[0.16em] text-[#027DD6]">What to expect</p><h2 className="mt-3 text-4xl font-bold text-slate-900">A simple support experience</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[["Choose your path","Start a new application or call about an existing order."],["Share the key details","Provide the brand or order information relevant to your request."],["Move to the next step","Receive confirmation and the next available service action."]].map(([title,copy],i)=><article key={title} className="relative rounded-3xl bg-white p-8 shadow-sm"><span className="absolute right-6 top-5 text-5xl font-black text-blue-50">0{i+1}</span><h3 className="relative text-xl font-bold text-slate-900">{title}</h3><p className="relative mt-4 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="px-5 py-24"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-2"><div className="rounded-3xl border border-blue-100 p-8"><FaRegClock className="text-3xl text-[#027DD6]" /><h2 className="mt-5 text-2xl font-bold text-slate-900">Support hours</h2><p className="mt-3 leading-7 text-slate-600">Monday through Friday<br />9:00 AM–6:00 PM</p></div><div className="rounded-3xl border border-blue-100 p-8"><IoCallSharp className="text-3xl text-[#027DD6]" /><h2 className="mt-5 text-2xl font-bold text-slate-900">Call customer support</h2><a href="tel:+13104244909" className="mt-3 block text-xl font-bold text-[#027DD6]">+1 (310) 424-4909</a><p className="mt-2 text-slate-600">Have your order email or receipt details ready.</p></div></div></section>
    <section className="px-5 pb-24"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-[#087bc3] to-[#55c3e9] px-8 py-14 text-center text-white"><h2 className="text-3xl font-bold md:text-5xl">Ready to start your trademark filing?</h2><Link href="/trademark-registration" className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-xl bg-white px-9 py-4 font-bold text-[#075A96]">Compare Registration Plans <FaArrowRightLong /></Link></div></section>
    <FooterSection />
  </main></>;
}
