import Header from "@/components/ui/Header";
import FooterSection from "@/components/sections/FooterSection";
import Link from "next/link";
import { FaArrowRightLong, FaCheck, FaRegCalendarCheck, FaRegClock, FaRegFolderOpen } from "react-icons/fa6";

export const metadata = { title: "Trademark Renewal Filing Support | Legal Trademark Office", description: "Organize the information needed for a U.S. trademark maintenance or renewal filing with clear customer review and filing support.", alternates: { canonical: "/services/trademark-renewal" } };

export default function RenewalPage() {
  return <><Header /><main className="overflow-hidden bg-white">
    <section className="relative bg-gradient-to-br from-[#edfbff] via-white to-[#e8fff8] px-5 py-28"><div className="soft-blob -right-12 top-10 bg-emerald-200" /><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-2"><div className="relative z-10"><p className="font-bold uppercase tracking-[0.18em] text-teal-600">Trademark renewal support</p><h1 className="mt-4 text-4xl font-bold leading-tight text-slate-900 md:text-6xl">Keep Your Trademark Ready for Its Next Chapter</h1><p className="mt-6 text-lg leading-8 text-slate-600">Bring your registration details and maintenance information into one guided renewal-support process.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/contact-us" className="soft-primary-btn !bg-teal-600">Start Renewal Support <FaArrowRightLong /></Link><Link href="tel:+13104244909" className="soft-secondary-btn">Call Customer Support</Link></div></div><div className="relative min-h-[450px]"><div className="renewal-calendar absolute inset-x-8 top-4 rounded-[2rem] bg-white p-8 shadow-2xl"><div className="flex items-center justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-100 text-2xl text-teal-700"><FaRegCalendarCheck /></span><span className="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-700">Stay organized</span></div><h2 className="mt-8 text-3xl font-bold text-slate-900">Renewal support checklist</h2><div className="mt-6 space-y-4">{["Registration details","Current owner information","Maintenance filing details"].map(item=><div key={item} className="flex items-center gap-3 rounded-xl bg-[#f3fcfa] p-4 font-semibold text-slate-700"><FaCheck className="text-teal-600" />{item}</div>)}</div></div><div className="soft-float-card absolute bottom-2 left-0"><FaRegClock className="text-teal-600" /><span>Keep the next step visible</span></div></div></div></section>
    <section className="px-5 py-20"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-3">{[[FaRegFolderOpen,"Everything in one place","Organize the registration record and current filing information."],[FaRegCalendarCheck,"A guided maintenance path","Follow a focused checklist for the selected renewal support."],[FaRegClock,"Clear service updates","Stay connected as the renewal-support order moves forward."]].map(([Icon,title,copy])=><article key={title} className="rounded-3xl border border-teal-100 bg-white p-8 shadow-sm transition hover:-translate-y-2 hover:shadow-xl"><Icon className="text-4xl text-teal-600" /><h2 className="mt-5 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></section>
    <section className="bg-[#f2fbfa] px-5 py-24"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><p className="font-bold uppercase tracking-[0.16em] text-teal-600">How renewal support works</p><h2 className="mt-3 text-4xl font-bold text-slate-900">A clear path for the details that matter</h2></div><div className="relative mt-14 grid gap-8 md:grid-cols-3"><div className="absolute left-[16%] right-[16%] top-7 hidden h-1 bg-gradient-to-r from-teal-200 via-teal-400 to-teal-200 md:block" />{[["Share your registration","Start with the registration number and current owner details."],["Complete the checklist","Provide the information requested for the maintenance support."],["Review the next step","Check the prepared details and move forward with confidence."]].map(([title,copy],i)=><article key={title} className="relative rounded-3xl bg-white p-8 text-center shadow-sm"><span className="relative z-10 mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-teal-600 text-xl font-bold text-white">{i+1}</span><h3 className="mt-6 text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="px-5 py-24"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-2"><div><p className="font-bold uppercase tracking-[0.16em] text-teal-600">Designed for busy brand owners</p><h2 className="mt-3 text-4xl font-bold text-slate-900">Spend less time sorting through renewal details</h2><p className="mt-5 leading-8 text-slate-600">A guided support workflow helps keep registration information, requested details and service updates together.</p><Link href="/contact-us" className="mt-7 inline-flex items-center gap-2 font-bold text-teal-700">Request renewal support <FaArrowRightLong /></Link></div><div className="grid gap-4 sm:grid-cols-2">{["Organized registration record","Focused information checklist","Customer review step","Post-purchase service updates"].map(item=><div key={item} className="flex items-center gap-3 rounded-2xl bg-[#effbf8] p-5 font-semibold text-slate-700"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-white text-teal-600 shadow-sm"><FaCheck /></span>{item}</div>)}</div></div></section>
    <section className="px-5 pb-24"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-teal-600 to-cyan-500 px-8 py-16 text-center text-white"><h2 className="text-3xl font-bold md:text-5xl">Ready to organize your trademark renewal?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-teal-50">Connect with customer support and start with your registration details.</p><Link href="/contact-us" className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-xl bg-white px-9 py-4 font-bold text-teal-700">Start Renewal Support <FaArrowRightLong /></Link></div></section>
    <FooterSection />
  </main></>;
}
