import Header from "@/components/ui/Header";
import FooterSection from "@/components/sections/FooterSection";
import Link from "next/link";
import { FaArrowRightLong, FaCheck, FaRegFileLines, FaRotate, FaRoute } from "react-icons/fa6";

export const metadata = { title: "Trademark Revival Filing Support | Legal Trademark Office", description: "Get organized filing support for an eligible U.S. trademark application that may require a revival request after abandonment.", alternates: { canonical: "/services/trademark-revival" } };

export default function RevivalPage() {
  return <><Header /><main className="overflow-hidden bg-white">
    <section className="relative bg-gradient-to-br from-[#eef8ff] via-white to-[#eaf7ff] px-5 py-28"><div className="soft-blob -left-16 bottom-0 bg-cyan-200" /><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="relative z-10"><p className="font-bold uppercase tracking-[0.18em] text-[#027DD6]">Trademark revival support</p><h1 className="mt-4 text-4xl font-bold leading-tight text-slate-900 md:text-6xl">Give Your Trademark Application a Fresh Next Step</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Bring the application record and notice into one focused support process designed to help you understand and prepare the next action.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/contact-us" className="soft-primary-btn !bg-[#027DD6]">Start Revival Support <FaArrowRightLong /></Link><Link href="tel:+13104244909" className="soft-secondary-btn">Call Customer Support</Link></div></div><div className="relative min-h-[440px]"><div className="revival-route-card absolute inset-x-5 top-8 rounded-[2rem] bg-white p-8 shadow-2xl"><div className="flex items-center justify-between"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-blue-100 text-3xl text-[#027DD6]"><FaRotate /></span><span className="rounded-full bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700">Next-step support</span></div><div className="mt-8 space-y-5">{[["1","Application record"],["2","Relevant notice"],["3","Prepared next step"]].map(([n,label],i)=><div key={label} className="relative flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#027DD6] font-bold text-white">{n}</span><span className="font-semibold text-slate-700">{label}</span>{i<2&&<span className="absolute left-[21px] top-11 h-5 w-px bg-cyan-200" />}</div>)}</div></div><div className="soft-float-card absolute bottom-4 right-0"><FaRoute className="text-[#027DD6]" /><span>A clear route forward</span></div></div></div></section>
    <section className="px-5 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-6 md:grid-cols-3">{[[FaRegFileLines,"Start with the record","Use the application record and notice as the starting point."],[FaRoute,"Follow a focused path","Collect the information connected to the next support step."],[FaRotate,"Move forward organized","Keep the prepared details and service updates easy to follow."]].map(([Icon,title,copy])=><article key={title} className="rounded-3xl bg-gradient-to-b from-blue-50 to-white p-8 shadow-sm transition hover:-translate-y-2 hover:shadow-xl"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-2xl text-[#027DD6] shadow-sm"><Icon /></span><h2 className="mt-6 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="bg-[#f4faff] px-5 py-24"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-bold uppercase tracking-[0.16em] text-[#027DD6]">What happens next</p><h2 className="mt-3 text-4xl font-bold text-slate-900">Three simple stages of revival support</h2><p className="mt-5 leading-8 text-slate-600">A guided workflow keeps the application information and selected service step together.</p></div><div className="space-y-5">{[["Share the serial number and notice","Give the support team the application information needed to begin."],["Complete the focused questions","Add the details requested for the selected revival-support service."],["Review the prepared next step","Check the information and continue with the applicable service action."]].map(([title,copy],i)=><article key={title} className="grid gap-4 rounded-3xl bg-white p-7 shadow-sm sm:grid-cols-[52px_1fr]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#027DD6] text-lg font-bold text-white">{i+1}</span><div><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-2 leading-7 text-slate-600">{copy}</p></div></article>)}</div></div></section>
    <section className="px-5 py-24"><div className="mx-auto max-w-5xl rounded-[2rem] border border-blue-100 bg-white p-8 shadow-xl md:p-14"><div className="grid gap-10 md:grid-cols-2"><div><h2 className="text-3xl font-bold text-slate-900">Support that keeps the next step understandable</h2><p className="mt-4 leading-8 text-slate-600">Bring the relevant information together and stay connected as the service progresses.</p></div><ul className="space-y-4">{["Application-record starting point","Focused information checklist","Customer review step","Service confirmation and updates"].map(item=><li key={item} className="flex items-center gap-3 font-semibold text-slate-700"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-[#027DD6]"><FaCheck /></span>{item}</li>)}</ul></div></div></section>
    <section className="px-5 pb-24"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-[#027DD6] to-[#3b82f6] px-8 py-16 text-center text-white"><h2 className="text-3xl font-bold md:text-5xl">Ready to review the next step for your application?</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-blue-50">Contact customer support with the application record and relevant notice.</p><Link href="/contact-us" className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-xl bg-white px-9 py-4 font-bold text-[#075A96]">Start Revival Support <FaArrowRightLong /></Link></div></section>
    <FooterSection />
  </main></>;
}
