import Header from "@/components/ui/Header";
import Image from "next/image";
import Link from "next/link";
import FooterSection from "@/components/sections/FooterSection";
import TMButton from "@/components/ui/TMButton";

export const metadata = { title: "Trademark Revival Filing Support | Legal Trademark Office", description: "Get organized filing support for an eligible U.S. trademark application that may require a revival request after abandonment.", alternates: { canonical: "/services/trademark-revival" } };

export default function TrademarkRevivalPage() {
  const benefits = [["Status review","Start with the application record and notice so the required next step is clear."],["Information preparation","Organize the filing details and supporting information needed for your review."],["Submission coordination","Approve the prepared information and receive updates as the selected service moves forward."]];
  return <><Header /><main className="bg-slate-100"><section className="bg-freeSearch min-h-[78vh] bg-cover bg-bottom px-5 py-28 flex items-center"><div className="mx-auto w-full max-w-5xl space-y-6"><p className="font-semibold uppercase tracking-[0.18em] text-blue-100">Trademark revival support</p><h1 className="max-w-3xl text-4xl font-bold leading-tight text-white md:text-5xl">Move an Eligible Trademark Revival Request Forward</h1><p className="max-w-2xl text-lg leading-8 text-slate-100">If a U.S. trademark application has an abandonment notice, our filing-support team can help organize the record, required information and next submission step.</p><div className="flex flex-wrap gap-4"><TMButton px="80px" py="30px" text="Start Now" /><Link href="/contact-us" className="rounded-lg border border-white px-10 py-4 font-semibold text-white">Contact support</Link></div></div></section><section className="px-5 py-20 md:py-28"><div className="mx-auto grid max-w-6xl items-center gap-12 md:grid-cols-2"><Image width={560} height={500} alt="Trademark revival filing support" src="/images/trademark-revival.jpg" className="rounded-2xl object-cover" /><div><p className="font-semibold text-[#027DD6]">A focused next step</p><h2 className="mt-2 text-3xl font-bold text-[#075A96]">Get clarity from notice to response</h2><p className="mt-5 text-lg leading-8 text-slate-600">Revival eligibility and requirements depend on the application record. We help collect and organize the relevant details so you can review the prepared filing information before submission.</p><div className="mt-8"><TMButton px="70px" py="30px" text="Begin Revival Support" /></div></div></div></section><section className="bg-[#E5F4FF] px-5 py-20"><div className="mx-auto max-w-6xl"><div className="text-center"><h2 className="text-3xl font-bold text-[#075A96]">Revival support built for action</h2><p className="mt-3 text-slate-600">A simple process that keeps the application record and next step together.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{benefits.map(([title,copy],i)=><article key={title} className="rounded-2xl bg-white p-7 shadow-sm"><span className="font-bold text-[#027DD6]">0{i+1}</span><h3 className="mt-4 text-xl font-bold text-[#075A96]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div><div className="mt-10 text-center"><Link href="/contact-us" className="inline-block rounded-lg bg-[#027DD6] px-10 py-4 font-semibold text-white">Request revival support</Link></div></div></section><FooterSection /></main></>;
}
