"use client";
import { useState } from "react";
import { HiOutlinePlus, HiOutlineTrash } from "react-icons/hi2";
import { PORTAL_PACKAGE_OPTIONS } from "@/constant/pricing";

const emptyMark=()=>({id:crypto.randomUUID(),markName:"",markType:"Word mark",packageName:""});
export default function PortalInviteForm({ demoMode=false, deliveryConfigured=true }){
  const [busy,setBusy]=useState(false);const [result,setResult]=useState(null);const [marks,setMarks]=useState([emptyMark()]);
  // React clears event.currentTarget once the handler yields, so the form
  // element has to be captured before the first await. Reading it afterwards
  // threw inside the try block and reported a network failure for an
  // invitation that had already been created and emailed.
  async function submit(event){event.preventDefault();setBusy(true);setResult(null);const formElement=event.currentTarget;const form=new FormData(formElement);const trademarks=marks.map(mark=>({markName:mark.markName.trim(),markType:mark.markType,packageName:mark.packageName})).filter(mark=>mark.markName);if(!trademarks.length){setResult({ok:false,text:"Add at least one trademark matter."});setBusy(false);return}if(demoMode){setResult({ok:true,text:`Preview complete for ${trademarks.length} trademark matter${trademarks.length>1?"s":""}. No account was created and no email was sent in preview mode.`});setBusy(false);return}try{const response=await fetch('/api/auth/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),email:form.get('email'),company:form.get('company'),trademarks})});const payload=await response.json();setResult({ok:response.ok,text:payload.message||payload.error});if(response.ok){formElement.reset();setMarks([emptyMark()])}}catch(error){console.error("Invitation request failed:",error);setResult({ok:false,text:"The invitation service is unavailable. Please try again."})}finally{setBusy(false)}}
  function updateMark(id,key,value){setMarks(items=>items.map(item=>item.id===id?{...item,[key]:value}:item))}
  return <form onSubmit={submit} className="min-w-0 space-y-5">
    {demoMode&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold leading-6 text-amber-900"><b>Preview mode:</b> this screen demonstrates the invitation workflow only. It does not create a Firebase account or send an email. Use the authenticated staff portal without <code className="rounded bg-amber-100 px-1">?preview=1</code> to send a real invitation.</div>}
    {!demoMode&&!deliveryConfigured&&<div className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-semibold leading-6 text-red-800"><b>Invitation delivery is not configured.</b> Firebase Admin server credentials must be added to the deployment environment before this page can create accounts and send secure setup links.</div>}
    {result&&<div className={`rounded-xl border p-4 text-sm font-semibold ${result.ok?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-700"}`}>{result.text}</div>}
    <div className="grid gap-5 md:grid-cols-2"><label className="min-w-0"><span className="text-sm font-bold">Client full name</span><input name="name" required className="input" placeholder="Alex North"/></label><label className="min-w-0"><span className="text-sm font-bold">Client login email</span><input name="email" type="email" required className="input" placeholder="alex@company.com"/></label></div>
    <label className="block min-w-0"><span className="text-sm font-bold">Company or owner name</span><input name="company" className="input" placeholder="Northstar Studio LLC"/></label>
    <section className="min-w-0 rounded-2xl border border-slate-200 bg-slate-50 p-3 sm:p-5"><div className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><h2 className="font-extrabold">Trademark matters</h2><p className="mt-1 text-xs leading-5 text-slate-500">Add every existing application this client should manage.</p></div><button type="button" onClick={()=>setMarks(items=>[...items,emptyMark()])} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-100 px-3 py-2.5 text-xs font-extrabold text-[#027dd6]"><HiOutlinePlus/> Add trademark</button></div><div className="mt-4 space-y-4">{marks.map((mark,index)=><article key={mark.id} className="min-w-0 rounded-xl border border-slate-200 bg-white p-3 sm:p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-extrabold uppercase text-[#027dd6]">Trademark {index+1}</p>{marks.length>1&&<button type="button" onClick={()=>setMarks(items=>items.filter(item=>item.id!==mark.id))} className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-red-600 hover:bg-red-50" aria-label={`Remove trademark ${index+1}`}><HiOutlineTrash/></button>}</div><div className="mt-3 grid min-w-0 gap-4 md:grid-cols-2 xl:grid-cols-3"><label className="min-w-0"><span className="text-xs font-bold">Trademark name</span><input value={mark.markName} onChange={e=>updateMark(mark.id,'markName',e.target.value)} required className="input" placeholder="Northstar Studio"/></label><label className="min-w-0"><span className="text-xs font-bold">Mark type</span><select value={mark.markType} onChange={e=>updateMark(mark.id,'markType',e.target.value)} className="input"><option>Word mark</option><option>Logo / design mark</option><option>Slogan</option><option>Sound mark</option></select></label><label className="min-w-0 md:col-span-2 xl:col-span-1"><span className="text-xs font-bold">Package</span><select value={mark.packageName} onChange={e=>updateMark(mark.id,'packageName',e.target.value)} className="input"><option value="">Not assigned</option>{PORTAL_PACKAGE_OPTIONS.map(option=><option key={option}>{option}</option>)}</select></label></div></article>)}</div></section>
    <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-slate-700"><b>Secure invitation:</b> the client receives their login email and a single-use password-creation link. No reusable password is sent by email.</div>
    <button disabled={busy||(!demoMode&&!deliveryConfigured)} className="w-full whitespace-normal rounded-xl bg-[#006fbd] px-4 py-4 text-center text-sm font-extrabold leading-5 text-white disabled:cursor-not-allowed disabled:opacity-60">{busy?"Creating secure invitation…":!demoMode&&!deliveryConfigured?"Invitation setup required":demoMode?`Preview invitation for ${marks.length} trademark${marks.length>1?"s":""}`:`Create client with ${marks.length} trademark${marks.length>1?"s":""} and send invitation`}</button>
  </form>;
}
