import LegalPage from "@/components/legal/LegalPage";

export const metadata = {
  title: "Refund Policy | Legal Trademark Office",
  description: "Review cancellation, service-fee, government-fee and refund-request rules for Legal Trademark Office filing-support orders.",
  alternates: { canonical: "/legal/refund-policy" },
};

export default function RefundPolicyPage() {
  return (
    <LegalPage title="Refund and Cancellation Policy">
      <section><h2 className="text-xl font-semibold text-slate-900">Before work begins</h2><p>You may request cancellation before substantive search, preparation or review work begins. Approved refunds are returned to the original payment method, less any non-refundable processing or third-party charge permitted by law.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">After work begins or an application is submitted</h2><p>Once substantive work has started, the earned portion of the service fee is non-refundable. After an application is submitted to the USPTO, the service fee for preparing and submitting that application is earned and non-refundable, except where required by applicable law or where a promised service was not delivered. If a service concern can be corrected, we will first make a reasonable effort to complete or correct the purchased work.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Government and third-party fees</h2><p>USPTO fees are generally not refunded after payment or submission, although the USPTO identifies limited circumstances in which a refund may be available. Completed third-party costs are non-refundable to the extent permitted by law. Review the <a className="underline" href="https://www.uspto.gov/learning-and-resources/fees-and-payment/refund-information" target="_blank" rel="noreferrer">USPTO refund information</a> for the government&apos;s current rules.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Package monitoring and recurring charges</h2><p>Any monitoring included in a package is provided for the stated number of months. Standard service packages are one-time purchases and do not renew monthly or annually. This is separate from future USPTO trademark maintenance filings, which follow federal deadlines. No recurring package or monitoring charge is made unless a future subscription is separately offered and affirmatively authorized.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Payment inquiries and disputes</h2><p>The payment receipt identifies the applicable card-statement descriptor after a successful payment. Before opening a dispute, contact us with the order email and transaction details so we can identify the charge and review the service record. We retain transaction authorizations, accepted agreement versions, case activity and delivery records to respond accurately to payment inquiries and disputes.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">No outcome-based refund</h2><p>A refusal, opposition, abandonment or failure to obtain registration does not automatically qualify for a refund. Trademark outcomes are controlled by the USPTO, the accuracy of customer information and possible third-party rights.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Our preparation errors</h2><p>If we make a clerical preparation error within the purchased scope, contact us promptly. We will review the order and, where reasonably possible, correct our work without an additional service charge. A correction does not include changed instructions, inaccurate customer-supplied information, a new filing requirement, government action or a third-party objection.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Requesting a review</h2><p>Submit a request through our contact page with the order email, receipt number and reason for the request. We will acknowledge the request and provide a written decision after reviewing the work already performed, expenses incurred and submission status. We may request additional information needed to verify the purchaser or transaction.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">How approved refunds are issued</h2><p>An approved refund is returned to the original payment method unless another method is required by the payment provider or applicable law. Bank and card-network processing times are outside our control. We will provide confirmation after the refund is submitted for processing.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Attorney services</h2><p>If a customer separately enters a written engagement for attorney services, cancellation and refund terms for that legal service are governed by the separately accepted engagement. Purchasing a standard filing-support package alone does not create an attorney-client relationship.</p></section>
    </LegalPage>
  );
}
