import nodemailer from "nodemailer";

const escapeHtml = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char]);

export async function sendPortalActivityEmail({ clientName, clientEmail, attorneyName, type, title, message, dueAt, amount, appointmentAt, meetingType, meetingUrl, phoneNumber, serialNumber, filingDate, documentUrl, classificationFees = [], transactionId = "" }) {
  if (!clientEmail) return;
  const portalUrl = `${(process.env.NEXT_PUBLIC_APP_URL || process.env.APP_URL || "https://www.legaltrademarkoffice.com").replace(/\/$/, "")}/portal-login`;
  const documentHref = documentUrl?.startsWith("/") ? `${new URL(portalUrl).origin}${documentUrl}` : documentUrl;
  const labels = { status: "Application status updated", task: "New task assigned", requirement: "New legal requirement", document: "Document requested", message: "New secure message", promotion: "A recommendation from your client team", email: "Message from your attorney", payment: "Payment requested", payment_receipt: "Payment receipt", appointment: "Call scheduled", appointment_request: "Attorney call required", filing: "Your trademark application was filed", clearance_report: "Your attorney’s clearance report is ready" };
  const subject = `${labels[type] || "Client portal update"}${title ? ` — ${title}` : ""}`;
  const itemizedFees = Array.isArray(classificationFees) && classificationFees.length ? `<div style="margin:16px 0;padding:14px;background:#f8fafc;border-radius:10px"><b>Itemized classifications</b>${classificationFees.map((item) => `<p style="margin:8px 0">${escapeHtml(item.description)} <span style="float:right;font-weight:700">$${Number(item.amount || 0).toFixed(2)}</span></p>`).join("")}</div>` : "";
  const details = [dueAt ? `<p style="margin:8px 0"><b>Due:</b> ${escapeHtml(dueAt)}</p>` : "", itemizedFees, Number(amount) > 0 ? `<p style="margin:8px 0"><b>Total:</b> $${Number(amount).toFixed(2)} USD</p>` : "", transactionId ? `<p style="margin:8px 0"><b>Transaction:</b> ${escapeHtml(transactionId)}</p>` : "", appointmentAt ? `<p style="margin:8px 0"><b>Appointment:</b> ${escapeHtml(appointmentAt)}</p>` : "", meetingType === "google_meet" && meetingUrl ? `<p style="margin:16px 0"><a href="${escapeHtml(meetingUrl)}" style="color:#087dcc;font-weight:700">Join Google Meet</a></p>` : "", meetingType === "phone" && phoneNumber ? `<p style="margin:8px 0"><b>Phone call:</b> <a href="tel:${escapeHtml(phoneNumber)}">${escapeHtml(phoneNumber)}</a></p>` : "", serialNumber ? `<p style="margin:8px 0"><b>USPTO serial number:</b> ${escapeHtml(serialNumber)}</p>` : "", filingDate ? `<p style="margin:8px 0"><b>Filed:</b> ${escapeHtml(filingDate)}</p>` : "", documentHref ? `<p style="margin:16px 0"><a href="${escapeHtml(documentHref)}" style="color:#087dcc;font-weight:700">Download ${type === "clearance_report" ? "attorney clearance report" : "filing document"}</a></p>` : ""].join("");
  const html = `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#0f172a"><table role="presentation" width="100%"><tr><td style="padding:32px 14px"><div style="max-width:620px;margin:auto;border-radius:18px;background:#fff;overflow:hidden"><div style="background:#087dcc;padding:26px;color:#fff"><div style="font-size:20px;font-weight:800">Legal Trademark Office®</div><div style="margin-top:5px;font-size:13px">Secure client update</div></div><div style="padding:30px"><p style="margin:0;color:#475569">Hello ${escapeHtml(clientName || "Client")},</p><h1 style="margin:16px 0 10px;font-size:25px">${escapeHtml(labels[type] || "Your case was updated")}</h1>${title ? `<h2 style="margin:0 0 12px;font-size:17px;color:#087dcc">${escapeHtml(title)}</h2>` : ""}<p style="color:#334155;font-size:15px;line-height:1.7">${escapeHtml(message || "Please sign in to review the latest update.")}</p>${details}<a href="${portalUrl}" style="display:inline-block;margin-top:22px;border-radius:11px;background:#006fbd;padding:13px 20px;color:#fff;text-decoration:none;font-weight:700">Open secure client portal</a><p style="margin-top:24px;color:#64748b;font-size:12px;line-height:1.6">Sent by ${escapeHtml(attorneyName || "your Legal Trademark Office team")}. For security, sign in through the portal before uploading documents or sharing sensitive information.</p></div></div></td></tr></table></body></html>`;
  const transporter = nodemailer.createTransport({ host: process.env.SMTP_HOST || undefined, port: Number(process.env.SMTP_PORT || 465), secure: process.env.SMTP_SECURE ? process.env.SMTP_SECURE === "true" : true, service: process.env.SMTP_HOST ? undefined : "gmail", auth: { user: process.env.SUPPORT_EMAIL || process.env.MAILER_EMAIL, pass: process.env.SUPPORT_EMAIL_PASSWORD || process.env.MAILER_PASSWORD } });
  await transporter.sendMail({ from: `Legal Trademark Office <${process.env.SUPPORT_EMAIL || process.env.MAILER_EMAIL}>`, to: clientEmail, replyTo: process.env.SUPPORT_EMAIL || process.env.MAILER_EMAIL, subject, html });
}

export async function sendAttorneyInvitationEmail({ name, email, setupUrl }) {
  const transporter = nodemailer.createTransport({ host: process.env.SMTP_HOST || undefined, port: Number(process.env.SMTP_PORT || 465), secure: process.env.SMTP_SECURE ? process.env.SMTP_SECURE === "true" : true, service: process.env.SMTP_HOST ? undefined : "gmail", auth: { user: process.env.SUPPORT_EMAIL || process.env.MAILER_EMAIL, pass: process.env.SUPPORT_EMAIL_PASSWORD || process.env.MAILER_PASSWORD } });
  const html = `<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif"><div style="max-width:600px;margin:32px auto;background:#fff;border-radius:18px;overflow:hidden"><div style="background:#087dcc;padding:26px;color:#fff;font-size:20px;font-weight:800">Legal Trademark Office® Attorney Portal</div><div style="padding:30px;color:#0f172a"><h1 style="font-size:25px">Welcome, ${escapeHtml(name)}</h1><p style="color:#334155;line-height:1.7">You have been granted attorney access to manage client matters, case requirements, messages, appointments and payment requests.</p><p style="color:#334155"><b>Login email:</b> ${escapeHtml(email)}</p><a href="${escapeHtml(setupUrl)}" style="display:inline-block;margin-top:18px;background:#006fbd;color:#fff;text-decoration:none;padding:13px 20px;border-radius:11px;font-weight:700">Create my attorney password</a><p style="margin-top:22px;color:#64748b;font-size:12px">This single-use link is time-limited. Do not share attorney access credentials.</p></div></div></body></html>`;
  await transporter.sendMail({ from: `Legal Trademark Office <${process.env.SUPPORT_EMAIL || process.env.MAILER_EMAIL}>`, to: email, subject: "Your Legal Trademark Office attorney access", html });
}

export async function sendAttorneyActivityEmail({ clientName, clientEmail, type, title, message }) {
  const recipient=process.env.ATTORNEY_NOTIFICATION_EMAIL||process.env.SUPPORT_EMAIL||process.env.MAILER_EMAIL;if(!recipient)return;
  const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST||undefined,port:Number(process.env.SMTP_PORT||465),secure:process.env.SMTP_SECURE?process.env.SMTP_SECURE==="true":true,service:process.env.SMTP_HOST?undefined:"gmail",auth:{user:process.env.SUPPORT_EMAIL||process.env.MAILER_EMAIL,pass:process.env.SUPPORT_EMAIL_PASSWORD||process.env.MAILER_PASSWORD}});
  const html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><div style="background:#087dcc;color:#fff;padding:24px;font-size:20px;font-weight:800">Attorney Portal Notification</div><div style="padding:26px;border:1px solid #e2e8f0"><p style="color:#64748b">Client activity</p><h1 style="font-size:23px">${escapeHtml(title||"New client update")}</h1><p><b>Client:</b> ${escapeHtml(clientName)} (${escapeHtml(clientEmail)})</p><p><b>Type:</b> ${escapeHtml(type)}</p><p style="line-height:1.7">${escapeHtml(message)}</p><a href="${(process.env.NEXT_PUBLIC_APP_URL||process.env.APP_URL||"https://www.legaltrademarkoffice.com").replace(/\/$/,"")}/portal-admin" style="display:inline-block;margin-top:18px;background:#006fbd;color:#fff;text-decoration:none;padding:12px 18px;border-radius:10px;font-weight:700">Open attorney portal</a></div></div>`;
  await transporter.sendMail({from:`Legal Trademark Office <${process.env.SUPPORT_EMAIL||process.env.MAILER_EMAIL}>`,to:recipient,subject:`Client portal: ${title||"new activity"}`,html});
}
