export const portalDemoClients = {
  northstar: {
    password: "Northstar2026!",
    user: { name: "Alex North", email: "alex@northstarstudio.example", role: "client" },
    case: { id: "LTO-2026-08147", markName: "Northstar Studio", company: "Northstar Studio LLC", markType: "Word mark", stage: "Classes and USPTO filing fees", progress: 48, packageName: "Premium", orderTotal: 649, openTasks: 0, appointment: "August 10, 2026", appointmentTime: "11:30 AM PT", consultationStatus: "completed", clearanceReportStatus: "ready", classificationPaymentStatus: "due", assignedAttorney: { uid: "attorney-danish", name: "Danish Khan", title: "Trademark attorney", email: "danish@legaltrademarkoffice.com" }, applicationDetails: { ownerType: "Limited liability company", organizationType: "LLC", stateFormation: "California", trademarkCurrentlyBeingUsed: "Yes", firstAnywhereDate: "2024-03-12", firstCommenceDate: "2024-05-01", selectedActivities: ["Downloadable business software", "Brand strategy and marketing consulting", "Business training workshops", "Website design and development"], estimatedClassCount: 4, reviewPreference: "Attorney to finalize classes" }, selectedClasses: ["Class 9 — Downloadable business software", "Class 35 — Advertising and business consulting", "Class 41 — Business training and educational workshops", "Class 42 — Website and software design"] },
  },
  asteria: {
    password: "Asteria2026!",
    user: { name: "Maya Rivera", email: "maya@asteriawellness.example", role: "client" },
    case: { id: "LTO-2026-08132", markName: "Asteria Wellness", company: "Asteria Wellness Co.", markType: "Logo / design mark", stage: "Mandatory attorney consultation", progress: 25, packageName: "Standard", orderTotal: 349, openTasks: 0, appointment: "August 12, 2026", appointmentTime: "2:00 PM PT", consultationStatus: "scheduled", assignedAttorney: { uid: "attorney-maya", name: "Maya Patel", title: "Senior trademark attorney", email: "maya@legaltrademarkoffice.com" }, applicationDetails: { ownerType: "Corporation", organizationType: "Corporation", stateFormation: "Delaware", trademarkCurrentlyBeingUsed: "No", selectedActivities: ["Wellness coaching", "Online health education"], estimatedClassCount: 2, reviewPreference: "Attorney to finalize classes" }, selectedClasses: [] },
  },
  journey: {
    password: "Journey2026!",
    user: { name: "Jordan Lee", email: "jordan@harborpine.example", role: "client" },
    case: { id: "LTO-DEMO-10001", markName: "Harbor & Pine", company: "Harbor & Pine Goods LLC", markType: "Word mark", stage: "Application received", progress: 12, packageName: "Advanced", orderTotal: 249, openTasks: 0, appointment: "To be scheduled", appointmentTime: "", consultationStatus: "pending", clearanceReportStatus: "pending", classificationPaymentStatus: "not_requested", assignedAttorney: { uid: "attorney-danish", name: "Danish Khan", title: "Trademark attorney", email: "danish@legaltrademarkoffice.com" }, applicationDetails: { ownerType: "Limited liability company", organizationType: "LLC", stateFormation: "Oregon", trademarkCurrentlyBeingUsed: "Yes", firstAnywhereDate: "2025-11-10", firstCommenceDate: "2026-01-15", selectedActivities: ["Home décor retail services", "Online retail store services", "Candles and home fragrance products"], estimatedClassCount: 0, reviewPreference: "Attorney to finalize classes" }, selectedClasses: [] },
  },
};
