import { FieldValue } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { getPortalUser, isTrustedPortalOrigin } from "@/lib/portalAuth";
import { getAdminFirestore } from "@/lib/firebaseAdmin";
import { requestEvidence } from "@/lib/paymentEvidence";

async function context(request,params){if(!isTrustedPortalOrigin(request))return{error:NextResponse.json({error:"Invalid request origin."},{status:403})};const user=await getPortalUser();if(!user||user.role!=="client")return{error:NextResponse.json({error:"Client access required."},{status:401})};const db=getAdminFirestore();if(!db)return{error:NextResponse.json({error:"Portal database is not configured."},{status:503})};const id=String(params.id||"").replace(/[^A-Za-z0-9_-]/g,"").slice(0,180);const clientRef=db.collection("portalClients").doc(user.uid);const methodRef=clientRef.collection("billingMethods").doc(id);const snapshot=await methodRef.get();if(!snapshot.exists)return{error:NextResponse.json({error:"Saved payment method not found."},{status:404})};return{user,clientRef,methodRef,method:snapshot.data()}}

export async function PATCH(request,{params}){const ctx=await context(request,params);if(ctx.error)return ctx.error;try{const body=await request.json();if(body.action!=="revoke_attorney_authorization")return NextResponse.json({error:"Unsupported billing action."},{status:400});await ctx.methodRef.set({attorneyInitiatedChargesAuthorized:false,attorneyChargeRevokedAt:FieldValue.serverTimestamp(),attorneyChargeMaximum:0,attorneyChargeCategories:[]},{merge:true});await ctx.clientRef.collection("auditLog").add({event:"client_revoked_attorney_charge_authorization",billingMethodId:ctx.methodRef.id,actorUid:ctx.user.uid,actorRole:ctx.user.role,createdAt:FieldValue.serverTimestamp(),...requestEvidence(request)});return NextResponse.json({success:true})}catch{return NextResponse.json({error:"Unable to revoke authorization."},{status:500})}}

export async function DELETE(request,{params}){const ctx=await context(request,params);if(ctx.error)return ctx.error;try{const securityKey=process.env.NMI_SECURITY_KEY;if(!securityKey)return NextResponse.json({error:"Payment service is not configured."},{status:503});const gatewayUrl=process.env.NMI_GATEWAY_URL||"https://secure.nmi.com";const gatewayParams=new URLSearchParams({security_key:securityKey,customer_vault:"delete_customer",customer_vault_id:ctx.method.customerVaultId});const response=await fetch(`${gatewayUrl}/api/transact.php`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:gatewayParams.toString()});const gateway=Object.fromEntries(new URLSearchParams(await response.text()));if(gateway.response!=="1")return NextResponse.json({error:gateway.responsetext||"The secure payment provider could not remove this saved card."},{status:400});await ctx.methodRef.set({status:"removed",removedAt:FieldValue.serverTimestamp(),attorneyInitiatedChargesAuthorized:false,attorneyChargeMaximum:0,attorneyChargeCategories:[]},{merge:true});await ctx.clientRef.collection("auditLog").add({event:"client_removed_saved_payment_method",billingMethodId:ctx.methodRef.id,actorUid:ctx.user.uid,actorRole:ctx.user.role,createdAt:FieldValue.serverTimestamp(),...requestEvidence(request)});return NextResponse.json({success:true})}catch{return NextResponse.json({error:"Unable to remove the saved method."},{status:500})}}
