import LegalPage from "@/components/legal/LegalPage";

export const metadata = {
  title: "Privacy Policy | Legal Trademark Office",
  description: "Learn what information Legal Trademark Office LLC collects, why it is used, when it is shared and the privacy choices available to users.",
  alternates: { canonical: "/legal/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy">
      <section><h2 className="text-xl font-semibold text-slate-900">Who controls the information</h2><p>Legal Trademark Office LLC, a Virginia limited liability company, operates this website and is responsible for the personal information described in this policy.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Information we collect</h2><p>Depending on how you use the website, we may collect contact details; trademark owner, mark, goods or services and filing information; account and portal activity; communications and uploaded documents; order, receipt and transaction records; and device, browser, IP address, cookie, advertising-attribution and website-usage information. We do not intentionally request information that is unrelated to providing or securing the service.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Where information comes from</h2><p>Information comes from you, an authorized person acting for you, your use of the website, service providers that help operate the service, and public government trademark records when needed to support an order.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">How information is used</h2><p>Information is used to communicate with you, prepare requested services, process payments, maintain records, improve the website and attribute advertising conversions.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">When information is disclosed</h2><p>We disclose information only as reasonably needed to provide and secure the requested service. Recipients may include Google Ads for advertising attribution, Zoho CRM for lead and customer relationship management, our payment-gateway and card-processing providers, and vendors supporting hosting, databases, email, customer support, analytics, security and professional services. Information may also be disclosed when required by law, to protect users or the service, in connection with a business transfer, or with your direction or consent. We do not sell payment-card information.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Public trademark records</h2><p>Information submitted in a trademark application—including certain owner names and addresses—may become publicly available through government records. We will explain filing information before submission.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Cookies and advertising</h2><p>We use cookies and similar technology for essential functionality, Google Ads conversion measurement, analytics, session replay and customer support. Where required, consent controls are presented before non-essential tracking begins. Advertising and analytics settings may be limited through browser or device controls.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Payments and security</h2><p>Card details are tokenized by our payment gateway and are not stored by this website. If you choose to save a payment method, the payment provider retains the card credentials in its secure vault and we retain only the vault reference, transaction identifiers and consent record. We use administrative, technical and organizational safeguards designed to protect information, but no internet transmission or storage system can be guaranteed completely secure.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Retention</h2><p>We retain information for the time reasonably needed to deliver services, maintain application and transaction records, meet accounting or legal obligations, prevent fraud, resolve disputes and enforce agreements. Retention depends on the type of record and purpose. Information is deleted or de-identified when it is no longer reasonably required, subject to legal and operational exceptions.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Your privacy choices</h2><p>Depending on your state and applicable law, you may request access to, a copy of, correction of or deletion of personal information, and may request information about certain disclosures. You may opt out of marketing using the message instructions. Some rights are not absolute, and application, security and transaction records may need to be retained. We may verify your identity and authority before completing a request and will not discriminate against you for exercising an applicable privacy right.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Authorized requests and appeals</h2><p>Where applicable, an authorized agent may submit a request with evidence of authority. If a privacy request is denied, you may ask us to review that decision through the same contact method. We will explain the result subject to applicable law.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Children</h2><p>The website and filing-support services are intended for adults and are not directed to children under 13. We do not knowingly collect personal information from children under 13 through the service.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Policy changes and contact</h2><p>We may update this policy as our practices or legal requirements change. The current update date appears on this page. Privacy questions and requests may be submitted through our contact page or mailed to Legal Trademark Office LLC, 2121 Crystal Dr, Arlington, VA 22202, USA.</p></section>
    </LegalPage>
  );
}
