import LegalPage from "@/components/legal/LegalPage";

export const metadata = {
  title: "Terms of Service | Legal Trademark Office",
  description: "Terms governing use of Legal Trademark Office LLC trademark filing-support services, fees, customer authorization and website access.",
  alternates: { canonical: "/legal/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <section><h2 className="text-xl font-semibold text-slate-900">Contracting company</h2><p>These Terms are an agreement between you and Legal Trademark Office LLC, a Virginia limited liability company operating the Legal Trademark Office website and filing-support service.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Acceptance and eligibility</h2><p>By using the website, creating an order or accepting these Terms at checkout, you agree to these Terms and the Privacy and Refund Policies. You must be at least 18 years old and legally able to enter a contract. If you order for a business or another organization, you confirm that you have authority to act for it.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Independent filing support</h2><p>Legal Trademark Office is an independent trademark filing support service and is not the USPTO or another government agency. Our specialized preparation team carefully organizes and reviews the application information supplied by each customer for common completeness and consistency issues against current filing requirements. This careful preparation is designed to reduce avoidable filing errors and give each application a stronger, more complete starting point. The USPTO independently examines every application, so purchasing a service does not guarantee acceptance or registration.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Scope of service</h2><p>Your package includes only the services shown in the package description and order summary. Government filings, additional classes, statements of use, extensions, office-action responses and other later work are excluded unless the order expressly says otherwise.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Customer as the trademark applicant</h2><p>Each order is prepared for the individual person or business identified by the customer. The customer, or the customer&apos;s identified business entity, remains the trademark applicant and owner. We use the owner, domicile, contact, trademark and goods or services information supplied and approved by the customer; we do not substitute Legal Trademark Office, its personnel or an unrelated party as the trademark owner or applicant. The customer is responsible for ensuring that all submitted information is complete, current and accurate.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Customer responsibilities</h2><p>You agree to respond to requests for information, review prepared details promptly, keep contact information current, protect account credentials and avoid submitting false, unlawful or third-party confidential information without authority. Delays, missed deadlines or additional work caused by incomplete, inaccurate or late information may affect service timing and may require a separate service or fee that you must approve.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Preparation, authorization and filing</h2><p>Our filing-support service helps organize and prepare application information for submission at the customer&apos;s request. The customer will have an opportunity to review material filing information and must provide any authorization, verification or signature required from the owner. A submission will be made only through a person permitted to make that submission under applicable USPTO rules. Purchasing filing support alone does not create an attorney-client relationship or authorize us to provide legal advice or legal representation.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Optional or required attorney services</h2><p>Attorney services are not automatically included in every filing-support package. If a matter requires legal judgment or representation, if USPTO rules require representation, or if the customer separately purchases a service that expressly includes attorney involvement, we may offer to assign or engage a U.S.-licensed attorney based on the matter&apos;s needs and availability. Any attorney-client relationship, scope of representation, fees and responsible attorney must be separately confirmed in writing after conflict and eligibility review. Until that confirmation occurs, no attorney-client relationship exists.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Fees and authorization</h2><p>The checkout total is the service charge authorized and collected today. The USPTO filing fee is displayed separately and charged per class. We will confirm the number of classes and request authorization before collecting government fees. Service fees are earned as work is performed and are non-refundable after USPTO submission, subject to applicable law and the Refund Policy. USPTO fees are generally non-refundable, with limited exceptions controlled by the USPTO. Payment details and the applicable card-statement descriptor are provided on the receipt after a successful payment.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Optional saved payment method</h2><p>If you affirmatively select the saved-payment option, our secure payment provider stores the payment credentials in its protected customer vault and we retain only the vault reference and related transaction identifiers. Saving a payment method does not authorize an additional charge. You must separately approve each future fee before it is charged.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">No automatic package renewal</h2><p>Current trademark filing-support packages and their stated monitoring periods do not renew automatically. A future subscription or renewal service would require a separate description of its price, duration and cancellation terms together with the customer&apos;s affirmative authorization before any recurring charge.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Electronic records and payment evidence</h2><p>You agree that electronic acceptance, transaction records, IP address, browser information, timestamps, portal messages, uploaded documents and service-delivery activity may be retained as business records. We may provide relevant records to our payment provider, card networks, banks or other payment participants to investigate a payment inquiry or dispute, subject to our Privacy Policy and applicable law.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Timing</h2><p>Processing estimates refer to our preparation time after receiving complete information. They do not expedite or predict USPTO examination, which is controlled by the government.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">No legal guarantee</h2><p>Trademark searches cannot identify every possible conflict. The USPTO or third parties may object to an application. Any attorney-client relationship, if offered, must be separately confirmed in writing after appropriate review.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Electronic communications</h2><p>You consent to receiving transactional calls, texts and emails about your application. Marketing communications may be declined using the instructions provided in the message.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Corrections and service concerns</h2><p>If we make a clerical preparation error within the purchased scope, notify us promptly and we will review the record and, where reasonably possible, correct our work without an additional service charge. This does not cover new customer instructions, inaccurate customer-supplied information, government action or third-party objections.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Third-party and government services</h2><p>The website may link to the USPTO and other third-party services. Their availability, security, processing times, decisions and terms are outside our control. Use of a third-party service may be governed by its own terms and privacy policy.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Website content and permitted use</h2><p>The website, branding, layout and original content are owned by or licensed to Legal Trademark Office LLC and are provided for personal or internal business use. You may not interfere with the website, attempt unauthorized access, misuse automated systems, impersonate another person, copy the service for resale or use the website for unlawful activity.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Availability and changes</h2><p>We may maintain, improve or discontinue website features and may update these Terms as services or legal requirements change. The current version and its update date will appear on this page. Changes apply prospectively unless applicable law requires otherwise.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Severability and entire agreement</h2><p>If a provision is found unenforceable, the remaining provisions continue to apply. These Terms, the order summary, Refund Policy, Privacy Policy and any separately accepted service agreement form the agreement for the purchased service. A separately signed attorney engagement controls only the legal service described in that engagement.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900">Questions and notices</h2><p>Questions about these Terms or an order may be sent through our contact page or mailed to Legal Trademark Office LLC, 2121 Crystal Dr, Arlington, VA 22202, USA. We may verify identity and order information before discussing a customer matter.</p></section>
    </LegalPage>
  );
}
