import { FieldValue } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { getPortalUser,isTrustedPortalOrigin } from "@/lib/portalAuth";
import { getAdminFirestore } from "@/lib/firebaseAdmin";
import { sendPortalActivityEmail } from "@/lib/portalEmail";
import { requestEvidence } from "@/lib/paymentEvidence";

export async function DELETE(request,{params}){
  if(!isTrustedPortalOrigin(request))return NextResponse.json({error:"Invalid request origin."},{status:403});const staff=await getPortalUser();if(!staff||!["admin","attorney"].includes(staff.role))return NextResponse.json({error:"Attorney access required."},{status:401});const db=getAdminFirestore();if(!db)return NextResponse.json({error:"Portal database is not configured."},{status:503});
  try{const clientRef=db.collection("portalClients").doc(params.uid);const activityRef=clientRef.collection("activity").doc(params.id);const [activitySnapshot,clientSnapshot]=await Promise.all([activityRef.get(),clientRef.get()]);if(!activitySnapshot.exists)return NextResponse.json({error:"Task not found."},{status:404});const item=activitySnapshot.data();if(!["task","requirement","document"].includes(item.type))return NextResponse.json({error:"Only client tasks and document requirements can be removed here."},{status:400});await activityRef.delete();const tasks=await clientRef.collection("tasks").where("activityId","==",params.id).get();await Promise.all(tasks.docs.map(doc=>doc.ref.delete()));const cancellation={type:"requirement_cancelled",title:`Request removed: ${item.title||"Client requirement"}`,message:"Your attorney removed this request. No further action is required unless you receive a new update.",caseId:item.caseId||"",createdBy:staff.uid,createdByName:staff.name,createdAt:FieldValue.serverTimestamp(),read:false};await clientRef.collection("activity").add(cancellation);await clientRef.collection("auditLog").add({event:"attorney_requirement_removed",activityId:params.id,caseId:item.caseId||"",removedItem:item,performedBy:staff.uid,performedByName:staff.name,performedByRole:staff.role,createdAt:FieldValue.serverTimestamp(),...requestEvidence(request)});const client=clientSnapshot.data()||{};try{await sendPortalActivityEmail({clientName:client.name,clientEmail:client.email,attorneyName:staff.name,...cancellation})}catch(error){console.error("Cancellation email failed:",error?.message)}return NextResponse.json({success:true})}catch{return NextResponse.json({error:"Unable to remove the requirement."},{status:500})}
}
