import { FieldValue } from "firebase-admin/firestore";
import { NextResponse } from "next/server";
import { getPortalUser,isTrustedPortalOrigin } from "@/lib/portalAuth";
import { getAdminFirestore } from "@/lib/firebaseAdmin";
import { sendAttorneyActivityEmail } from "@/lib/portalEmail";
import { requestEvidence } from "@/lib/paymentEvidence";

export async function POST(request){
  if(!isTrustedPortalOrigin(request))return NextResponse.json({error:"Invalid request origin."},{status:403});const user=await getPortalUser();if(!user||user.role!=="client")return NextResponse.json({error:"Client access required."},{status:401});const db=getAdminFirestore();if(!db)return NextResponse.json({error:"Portal database is not configured."},{status:503});
  try{const body=await request.json();const requestedType=String(body.type||"client_update").slice(0,60);const eventType=requestedType==="task_completed"?"task_response_submitted":requestedType;const event={clientUid:user.uid,clientName:user.name,clientEmail:user.email,type:eventType,title:String(body.title||"New client update").slice(0,180),message:String(body.message||"").slice(0,3000),caseId:String(body.caseId||"").slice(0,120),activityId:String(body.activityId||"").slice(0,160),read:false,createdAt:FieldValue.serverTimestamp()};const clientRef=db.collection("portalClients").doc(user.uid);let messageId="";if(["client_message","secure_message"].includes(event.type)&&event.message){const messageRef=await clientRef.collection("messages").add({caseId:event.caseId,body:event.message,senderId:user.uid,senderName:user.name||"Client",senderRole:"client",direction:"client_to_staff",readByStaff:false,createdAt:FieldValue.serverTimestamp()});messageId=messageRef.id;event.messageId=messageId}await db.collection("portalAttorneyNotifications").add(event);await clientRef.collection("auditLog").add({event:"client_portal_action",actionType:event.type,caseId:event.caseId,activityId:event.activityId,messageId,title:event.title,message:event.message,actorUid:user.uid,actorRole:user.role,createdAt:FieldValue.serverTimestamp(),...requestEvidence(request)});try{await sendAttorneyActivityEmail(event)}catch(error){console.error("Attorney notification email failed:",error?.message)}return NextResponse.json({success:true,messageId})}catch{return NextResponse.json({error:"Unable to notify the attorney."},{status:500})}
}
