import Header from "@/components/ui/Header";
import FooterSection from "@/components/sections/FooterSection";
import Link from "next/link";
import { FaArrowRightLong, FaCheck, FaRegLightbulb, FaRegMessage, FaRegStar } from "react-icons/fa6";

export const metadata = { title: "About Legal Trademark Office LLC | Filing Support", description: "Meet Legal Trademark Office LLC and see how our team helps customers prepare U.S. trademark applications through a simple guided process.", alternates: { canonical: "/about-us" } };

export default function AboutPage() {
  const services = [["Trademark registration","Prepare a new application for a name, logo or slogan."],["Trademark renewal","Organize information for an upcoming maintenance filing."],["Trademark revival","Get support with the next step for an eligible abandoned application."],["Application updates","Stay connected as your selected service moves forward."]];
  return <><Header /><main className="overflow-hidden bg-white">
    <section className="relative bg-gradient-to-br from-white via-[#f0f9ff] to-[#dff3ff] px-5 py-28"><div className="soft-blob -right-20 top-8 bg-cyan-200" /><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div className="relative z-10"><p className="font-bold uppercase tracking-[0.18em] text-[#027DD6]">About Legal Trademark Office</p><h1 className="mt-4 text-4xl font-bold leading-tight text-slate-900 md:text-6xl">Helping Brands Take the Next Trademark Step</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">We make trademark filing support easier to start, easier to follow and easier to manage—so business owners can keep building the brands they care about.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/trademark-registration" className="soft-primary-btn">Start Trademark Registration <FaArrowRightLong /></Link><Link href="/services" className="soft-secondary-btn">Explore our services</Link></div></div><div className="relative min-h-[440px]"><div className="about-visual-card absolute inset-x-6 top-8 rounded-[2rem] bg-white p-8 shadow-2xl"><p className="text-sm font-bold uppercase tracking-wide text-[#027DD6]">Your brand journey</p><h2 className="mt-3 text-3xl font-bold text-slate-900">Simple support from idea to filing</h2><div className="mt-7 grid gap-4">{["Tell us about your brand","Choose the support that fits","Review your prepared details"].map((item,i)=><div key={item} className="flex items-center gap-4 rounded-2xl bg-[#f4faff] p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#027DD6] font-bold text-white">{i+1}</span><span className="font-semibold text-slate-700">{item}</span></div>)}</div></div><div className="soft-float-card absolute bottom-3 left-0"><FaRegStar className="text-amber-500" /><span>Built for growing brands</span></div></div></div></section>
    <section className="px-5 py-20 md:py-28"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><p className="font-bold uppercase tracking-[0.16em] text-[#027DD6]">What we believe</p><h2 className="mt-3 text-3xl font-bold text-slate-900 md:text-5xl">A professional experience can still feel simple</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[[FaRegLightbulb,"Clarity first","Straightforward service choices and an easy starting point."],[FaRegMessage,"Human support","A support team available when customers need help with the process."],[FaRegStar,"Built for momentum","A guided workflow that helps brands move from decision to action."]].map(([Icon,title,copy])=><article key={title} className="rounded-3xl border border-blue-100 bg-[#f9fcff] p-8 transition hover:-translate-y-2 hover:shadow-xl"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-400 to-[#027DD6] text-2xl text-white"><Icon /></span><h3 className="mt-6 text-2xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
    <section className="bg-[#f3faff] px-5 py-24"><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-bold uppercase tracking-[0.16em] text-[#027DD6]">How we can help</p><h2 className="mt-3 text-4xl font-bold text-slate-900">Trademark support for different stages of your brand</h2><p className="mt-5 leading-8 text-slate-600">Choose the service that matches what your trademark needs today.</p></div><div className="grid gap-5 sm:grid-cols-2">{services.map(([title,copy])=><article key={title} className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-xl font-bold text-[#075A96]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p><Link href="/services" className="mt-5 inline-flex items-center gap-2 font-semibold text-[#027DD6]">Learn more <FaArrowRightLong /></Link></article>)}</div></div></div></section>
    <section className="px-5 py-24"><div className="mx-auto max-w-5xl rounded-[2rem] bg-gradient-to-r from-[#e8f7ff] to-white p-8 md:p-14"><div className="grid items-center gap-10 md:grid-cols-2"><div><h2 className="text-3xl font-bold text-slate-900">Why customers choose a guided start</h2><p className="mt-4 leading-8 text-slate-600">The right support helps bring important brand details into one clear workflow.</p></div><ul className="space-y-4">{["Focused online questionnaire","Service options for different needs","Customer review before the next filing step","Ongoing confirmation and service updates"].map(item=><li key={item} className="flex items-center gap-3 font-semibold text-slate-700"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><FaCheck /></span>{item}</li>)}</ul></div></div></section>
    <section className="px-5 pb-24"><div className="mx-auto max-w-6xl rounded-[2rem] bg-gradient-to-r from-[#087bc3] to-[#36b4e8] px-8 py-16 text-center text-white"><h2 className="text-3xl font-bold md:text-5xl">Your brand deserves a confident next step</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-blue-50">Compare trademark registration plans and begin when you are ready.</p><Link href="/trademark-registration" className="mt-8 inline-flex min-h-14 items-center gap-3 rounded-xl bg-white px-9 py-4 font-bold text-[#075A96]">View Registration Plans <FaArrowRightLong /></Link></div></section>
    <FooterSection />
  </main></>;
}
